name: BossesPlugin
version: '${project.version}'
main: com.wilmion.bossesplugin.BossesPlugin
api-version: 1.19
authors: [ Wilmion ]
description: Este es un plugin bien alaraco,
commands:
  bsspl:
    description: core comands for the Bosses Plugin
    usage: /<command> subCommand <args>

