name: BossesPlugin
version: '${project.version}'
main: com.wilmion.bossesplugin.BossesPlugin
api-version: 1.19
authors: [ Wilmion ]
description: Plugin de jefes en los mods naturales para una mayor dificultad,
commands:
  bsspl:
    description: Core comands for the Bosses Plugin
    usage: /bsspl <subcommands> <args>